ALTER TABLE "Paper" ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Anchor" ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Discussion" ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DiscussionReply" ADD COLUMN "isDemo" BOOLEAN NOT NULL DEFAULT false;
